; Emit deploy bash script from REPO_* keys

%ifndef KYTO_EMIT_DEPLOY_ASM
%define KYTO_EMIT_DEPLOY_ASM

section .data
    deploy_hdr  db "#!/usr/bin/env bash", 13, 10
                db "# Generated by Kyto ASM - do not edit.", 13, 10, 13, 10, 0
    export_pre  db "export ", 0
    export_eq   db "=", 34, 0
    export_end  db 34, 13, 10, 0

section .text

extern out_buf
extern strcat
extern deploy_keys
extern deploy_vals
extern deploy_count
extern path_deploy_script
extern write_text_file

global emit_deploy_file

emit_deploy_file:
    push    rbx
    cmp     dword [deploy_count], 0
    je      .out
    lea     rdi, [out_buf]
    mov     byte [rdi], 0
    mov     rcx, rdi
    lea     rdx, [deploy_hdr]
    call    strcat
    xor     ebx, ebx
.loop:
    mov     eax, ebx
    cmp     eax, [deploy_count]
    jae     .write
    mov     eax, ebx
    imul    eax, NAME_MAX
    lea     rsi, [deploy_keys + rax]
    mov     eax, ebx
    imul    eax, LINE_MAX
    lea     r8, [deploy_vals + rax]
    mov     rcx, rdi
    lea     rdx, [export_pre]
    call    strcat
    mov     rcx, rdi
    mov     rdx, rsi
    call    strcat_upper
    mov     rcx, rdi
    lea     rdx, [export_eq]
    call    strcat
    mov     rcx, rdi
    mov     rdx, r8
    call    strcat
    mov     rcx, rdi
    lea     rdx, [export_end]
    call    strcat
    inc     ebx
    jmp     .loop
.write:
    lea     rcx, [path_deploy_script]
    lea     rdx, [out_buf]
    call    write_text_file
.out:
    pop     rbx
    ret

; rcx=dst, rdx=src uppercase append
strcat_upper:
    push    rsi
    push    rdi
    mov     rdi, rcx
    mov     rsi, rdx
.find:
    cmp     byte [rdi], 0
    je      .copy
    inc     rdi
    jmp     .find
.copy:
    movzx   eax, byte [rsi]
    cmp     al, 'a'
    jb      .w
    cmp     al, 'z'
    ja      .w
    sub     al, 32
.w:
    mov     [rdi], al
    test    al, al
    jz      .done
    inc     rsi
    inc     rdi
    jmp     .copy
.done:
    pop     rdi
    pop     rsi
    ret

%endif
