; Emit users SQL, TypeScript, JSON

%ifndef KYTO_EMIT_USERS_ASM
%define KYTO_EMIT_USERS_ASM

section .data
    sql_hdr1    db "INSERT INTO ", 0
    sql_hdr2    db " (name, role, is_totp_setup, totp_secret)", 13, 10, "VALUES", 13, 10, 0
    sql_suffix  db 13, 10, "ON CONFLICT (name) DO NOTHING;", 13, 10, 0
    sql_row_pre db "  ('", 0
    sql_row_mid db "', '", 0
    sql_row_end db "', false, NULL)", 0
    ts_hdr      db "// Generated by Kyto ASM - do not edit.", 13, 10, 13, 10
                db "export const AUTHORIZED_USERS = [", 13, 10, 0
    ts_row_pre  db "  { name: ", 34, 0
    ts_row_mid  db 34, ", role: ", 34, 0
    ts_row_end  db 34, " as const },", 13, 10, 0
    ts_footer   db "] as const;", 13, 10, 13, 10
                db "export const AUTHORIZED_NAMES = [", 13, 10, 0
    ts_names_end db 13, 10, "] as const;", 13, 10, 13, 10
                db "export type AuthorizedUser = (typeof AUTHORIZED_USERS)[number];", 13, 10, 0
    role_admin  db "ADMIN", 0
    role_user   db "USER", 0
    comma_nl    db ",", 13, 10, 0
    json_quote  db 34, 0

section .text

extern out_buf
extern strcat
extern strcpy
extern is_admin_name
extern user_names
extern user_count
extern path_users_sql
extern path_users_ts
extern path_users_json
extern path_sql_table
extern write_text_file

global emit_users_files

emit_users_files:
    push    rbx
    cmp     dword [user_count], 0
    je      .out
    call    build_sql
    lea     rcx, [path_users_sql]
    lea     rdx, [out_buf]
    call    write_text_file
    call    build_ts
    lea     rcx, [path_users_ts]
    lea     rdx, [out_buf]
    call    write_text_file
    call    build_json
    lea     rcx, [path_users_json]
    lea     rdx, [out_buf]
    call    write_text_file
.out:
    pop     rbx
    ret

build_sql:
    push    rbx
    push    r12
    lea     rdi, [out_buf]
    mov     byte [rdi], 0
    mov     rcx, rdi
    lea     rdx, [sql_hdr1]
    call    strcat
    mov     rcx, rdi
    lea     rdx, [path_sql_table]
    call    strcat
    mov     rcx, rdi
    lea     rdx, [sql_hdr2]
    call    strcat
    xor     ebx, ebx
.row:
    mov     eax, ebx
    cmp     eax, [user_count]
    jae     .end
    imul    eax, NAME_MAX
    lea     r12, [user_names + rax]
    mov     rcx, rdi
    lea     rdx, [sql_row_pre]
    call    strcat
    mov     rcx, rdi
    mov     rdx, r12
    call    strcat
    mov     rcx, rdi
    lea     rdx, [sql_row_mid]
    call    strcat
    mov     rcx, r12
    call    is_admin_name
    mov     rcx, rdi
    test    rax, rax
    jnz     .adm
    lea     rdx, [role_user]
    jmp     .role
.adm:
    lea     rdx, [role_admin]
.role:
    call    strcat
    mov     rcx, rdi
    lea     rdx, [sql_row_end]
    call    strcat
    inc     ebx
    mov     eax, ebx
    cmp     eax, [user_count]
    jae     .end
    mov     rcx, rdi
    lea     rdx, [comma_nl]
    call    strcat
    jmp     .row
.end:
    mov     rcx, rdi
    lea     rdx, [sql_suffix]
    call    strcat
    pop     r12
    pop     rbx
    ret

build_ts:
    push    rbx
    push    r12
    lea     rdi, [out_buf]
    mov     byte [rdi], 0
    mov     rcx, rdi
    lea     rdx, [ts_hdr]
    call    strcat
    xor     ebx, ebx
.row:
    mov     eax, ebx
    cmp     eax, [user_count]
    jae     .footer
    mov     eax, ebx
    imul    eax, NAME_MAX
    lea     r12, [user_names + rax]
    mov     rcx, rdi
    lea     rdx, [ts_row_pre]
    call    strcat
    mov     rcx, rdi
    mov     rdx, r12
    call    strcat
    mov     rcx, rdi
    lea     rdx, [ts_row_mid]
    call    strcat
    mov     rcx, r12
    call    is_admin_name
    mov     rcx, rdi
    test    rax, rax
    jnz     .adm
    lea     rdx, [role_user]
    jmp     .role
.adm:
    lea     rdx, [role_admin]
.role:
    call    strcat
    mov     rcx, rdi
    lea     rdx, [ts_row_end]
    call    strcat
    inc     ebx
    jmp     .row
.footer:
    mov     rcx, rdi
    lea     rdx, [ts_footer]
    call    strcat
    xor     ebx, ebx
.name:
    mov     eax, ebx
    cmp     eax, [user_count]
    jae     .done
    mov     eax, ebx
    imul    eax, NAME_MAX
    lea     r12, [user_names + rax]
    mov     rcx, rdi
    lea     rdx, [json_quote]
    call    strcat
    mov     rcx, rdi
    mov     rdx, r12
    call    strcat
    mov     rcx, rdi
    lea     rdx, [json_quote]
    call    strcat
    inc     ebx
    mov     eax, ebx
    cmp     eax, [user_count]
    jae     .done
    mov     rcx, rdi
    lea     rdx, [comma_nl]
    call    strcat
    jmp     .name
.done:
    mov     rcx, rdi
    lea     rdx, [ts_names_end]
    call    strcat
    pop     r12
    pop     rbx
    ret

build_json:
    push    rbx
    push    r12
    lea     rdi, [out_buf]
    mov     byte [rdi], '['
    mov     byte [rdi + 1], 0
    xor     ebx, ebx
.loop:
    mov     eax, ebx
    cmp     eax, [user_count]
    jae     .end
    imul    eax, NAME_MAX
    lea     r12, [user_names + rax]
    mov     rcx, rdi
    lea     rdx, [json_quote]
    call    strcat
    mov     rcx, rdi
    mov     rdx, r12
    call    strcat
    mov     rcx, rdi
    lea     rdx, [json_quote]
    call    strcat
    inc     ebx
    mov     eax, ebx
    cmp     eax, [user_count]
    jae     .end
    mov     rcx, rdi
    lea     rdx, [json_sep]
    call    strcat
    jmp     .loop
.end:
    mov     rcx, rdi
    lea     rdx, [json_close]
    call    strcat
    pop     r12
    pop     rbx
    ret

json_sep:
    db ", ", 0
json_close:
    db "]", 13, 10, 0

%endif
